export const affirmations = [
  "You got this",
  "You'll figure it out",
  "I believe in you",
  "Sucking at something is the first step towards being good at something",
  "Struggling is part of learning",
  "Everything has cracks - that's how the light gets in",
  "Mistakes don't make you less capable",
  "We are all works in progress",
  "You are a capable human",
  "You know more than you think",
  "I am safe and cared for", 
  "I am safe and cared for", 
  "My opinion matters", 
  "I develop healthy relationships with the people I love", 
  "It’s okay to be overwhelmed, but I’ll be better soon", 
  "It’s okay to take a break", 
  "I nourish my mind, body, and soul", 
  "I am not different, I am just unique", 
  "I am ready to take on the day", 
  "I am hard-working", 
  "I develop positive, healthy relationships", 
  "It’s okay to ask for help", 
  "Mental health is just as important as physical health; take that break", 
  "I am all I need to be", 
  "I surround myself with the people I love", 
  "Call that friend to let them know that they matter to me", 
  "I am grateful for what I have", 
  "I deserve to treat myself for all that I have achieved", 
  "I am focused on living a peaceful life", 
  "All I need is within me right now",
  "I wake up motivated",
  "I am an unstoppable force of nature",
  "I am a living, breathing example of motivation",
  "I am not defined my by past; I am driven by my future",
  "I use obstacles to motivate me to learn and grow",
 " Today will be a productive day",
  "I am intelligent and focused",
  "I feel more grateful each day",
  "I am healing and strengthening every day",
  "I am allowed to say no when I feel like it",
  "I appreciate the unconditional support I get from those I love",
  "I commit to becoming the best version of myself",
  "I will try my best",
  "I will give and receive love in all my relationships",
  "I am the most authentic version of myself",
  "Asking for help is not a sign of weakness",
  "The choices I make are my own",
  "I belive that everything that happens, happens for a reason",
  "It's okay to not be okay",
  "I accept that I can't change what's behind me",
  "I'm worthy of my own love",
  "I'm a warrior. I've got this :)",
  "I must accept change to gain self-improvement",
  "I have the power to create my own happiness",
  "I can be selfish in order to prioritise myself"
];

